from __future__ import annotations

import json
from datetime import date
from typing import Dict, List

from .models import PRDAnalysisResult, RiskLevel, Task


class TaskFormatter:
    def to_json(self, result: PRDAnalysisResult, indent: int = 2) -> str:
        return result.model_dump_json(indent=indent)

    def to_dict(self, result: PRDAnalysisResult) -> dict:
        return json.loads(self.to_json(result))

    def to_jira_format(self, result: PRDAnalysisResult) -> List[dict]:
        """Convert tasks to Jira-compatible issue format."""
        issues = []
        for task in result.tasks:
            criteria_text = "\n".join(f"- {c}" for c in task.acceptance_criteria)
            issues.append(
                {
                    "summary": task.title,
                    "description": (
                        f"{task.description}\n\n"
                        f"**Acceptance Criteria:**\n{criteria_text}"
                    ),
                    "issuetype": {"name": "Story"},
                    "priority": {"name": self._risk_to_priority(task.risk_level)},
                    "labels": [f"effort:{task.effort_estimate.replace(' ', '_')}"],
                    "story_points": self._effort_to_points(task.effort_estimate),
                    "external_id": task.id,
                }
            )
        return issues

    def get_high_risk_tasks(self, result: PRDAnalysisResult) -> List[Task]:
        return [t for t in result.tasks if t.risk_level == RiskLevel.HIGH]

    def get_dependency_order(self, result: PRDAnalysisResult) -> List[Task]:
        """Return tasks in dependency order via topological sort."""
        task_map: Dict[str, Task] = {t.id: t for t in result.tasks}
        visited: set = set()
        order: List[Task] = []

        def dfs(task_id: str) -> None:
            if task_id in visited:
                return
            visited.add(task_id)
            task = task_map.get(task_id)
            if task:
                for dep_id in task.dependencies:
                    dfs(dep_id)
                order.append(task)

        for task in result.tasks:
            dfs(task.id)

        return order

    def to_markdown(self, result: PRDAnalysisResult) -> str:
        """Render the analysis result as a human-readable Markdown document."""
        lines: List[str] = []

        lines += [f"# {result.prd_title} — PRD Analysis", ""]
        lines += [f"*Generated by AI PRD Analyzer on {date.today()}*", "", "---", ""]

        # Summary
        lines += ["## Summary", ""]
        lines += ["| Metric | Value |", "|--------|-------|"]
        s = result.summary
        lines += [
            f"| Total Requirements | {s.total_requirements} |",
            f"| Functional | {s.functional_count} |",
            f"| Non-functional | {s.non_functional_count} |",
            f"| Ambiguities | {s.ambiguity_count} |",
            f"| Tasks | {s.total_tasks} |",
            f"| Estimated Total Effort | {s.estimated_total_effort} |",
        ]
        lines += ["", "---", ""]

        # Requirements grouped by type
        lines += ["## Requirements", ""]
        groups = [
            ("functional", "Functional Requirements"),
            ("non_functional", "Non-functional Requirements"),
            ("constraint", "Constraints"),
        ]
        for type_key, label in groups:
            reqs = [r for r in result.requirements if r.type.value == type_key]
            if not reqs:
                continue
            lines += [f"### {label}", ""]
            lines += ["| ID | Description | Priority | Section |",
                      "|----|-------------|----------|---------|"]
            for r in reqs:
                section = (r.source_section or "—").replace("|", "\\|")
                desc = r.description.replace("|", "\\|")
                lines.append(f"| {r.id} | {desc} | {r.priority.value} | {section} |")
            lines.append("")
        lines += ["---", ""]

        # Ambiguities
        if result.ambiguities:
            lines += ["## Ambiguities", ""]
            lines += ["> Clarify with PM before sprint start.", ""]
            for amb in result.ambiguities:
                lines += [f"### {amb.id} — {amb.location}", ""]
                lines += [f"**Issue:** {amb.issue}", ""]
                lines += [f"**Question:** {amb.clarifying_question}", ""]
            lines += ["---", ""]

        # Tasks
        lines += ["## Development Tasks", ""]
        for task in result.tasks:
            lines += [f"### {task.id}: {task.title}", ""]
            lines += ["| Property | Value |", "|----------|-------|"]
            deps = ", ".join(task.dependencies) if task.dependencies else "—"
            reqs_ref = ", ".join(task.related_requirements) if task.related_requirements else "—"
            lines += [
                f"| Effort | {task.effort_estimate} |",
                f"| Risk | {task.risk_level.value} |",
                f"| Dependencies | {deps} |",
                f"| Related Requirements | {reqs_ref} |",
            ]
            lines += ["", f"**Description:** {task.description}", ""]
            lines += ["**Acceptance Criteria:**", ""]
            for criterion in task.acceptance_criteria:
                lines.append(f"- [ ] {criterion}")
            lines.append("")

        return "\n".join(lines)

    def _risk_to_priority(self, risk_level: RiskLevel) -> str:
        return {"high": "High", "medium": "Medium", "low": "Low"}.get(
            risk_level.value, "Medium"
        )

    def _effort_to_points(self, effort_estimate: str) -> int:
        """Approximate story points from an effort estimate string."""
        s = effort_estimate.lower()
        if "0.5" in s or "half day" in s:
            return 1
        if "1 day" in s or "1-2 day" in s:
            return 2
        if any(x in s for x in ("2", "3")):
            return 5
        if any(x in s for x in ("4", "5")):
            return 8
        return 3
